--- 
# seems not working...
- name: Configure firewall. Ingnore if service is not running. 
  firewalld: service=postgresql permanent=true state=enabled
  ignore_errors: yes

# Rework?
- name: Find if pg cluster already exists.
  find: paths="{{ pg_data }}" file_type=file patterns="PG_VERSION"
  register: pg_dir

#- name: Initialize new postgresql cluster in default directory. If not already exists.
#  become: yes
#  become_user: "{{ postgresql_admin_user }}"
#  command: initdb -D {{ pg_data }}
#  when: pg_dir.matched|int == 0

- name: Initialize database
  command: /usr/pgsql-{{ postgresql_version }}/bin/initdb -D {{ pg_data }}
  when: ansible_distribution_major_version | int >= 7 and (pgdata_stat.stat.isdir is not defined or not pgdata_stat.stat.isdir)

- name: Start and enable postgresql service.
  service: 
    name: "{{ postgresql_distribution }}-{{ postgresql_version }}" 
    state: started 
    enabled: yes
