---
#- name: Download mamonsu repository script from package.cloud.io
#  get_url: 
#    url: https://packagecloud.io/install/repositories/postgrespro/mamonsu/script.rpm.sh
#    dest: /tmp/script.rpm.sh
#    mode: 0440

#- name: Run repo installer script
#  command: bash /tmp/script.rpm.sh

#- name: Install mamonsu.
#  yum: 
#    state: latest
#    pkg: "{{ item }}"
#  with_items:
#    - mamonsu

- name: Add mamonsu user.
  user: 
    name: mamonsu
    comment: mamonsu monitoring user
    createhome: yes
    home: /var/run/mamonsu
    shell: /sbin/nologin
    state: present

- name: Install mamonsu(pip)
  pip:
    name: mamonsu
    state: latest

- name: Copy unit from template.
  template: owner=root group=root mode=755
            src=mamonsu_init.j2
            dest=/etc/init.d/mamonsu

- name: Create mamonsu etc directory
  file: path=/etc/mamonsu/plugins state=directory mode=0755

- name: Create mamonsu log directory
  file: path=/var/log/mamonsu owner=mamonsu group=mamonsu state=directory mode=0755

- name: Copy agent.conf template 
  template: owner=root group=root mode=644 
            src=mamonsu_agent.conf.j2
            dest=/etc/mamonsu/agent.conf
  notify:
    - restart mamonsu

- postgresql_user:
    name: mamonsu
    port: "{{ postgresql_port }}"
  become_user: postgres

- name: Create Mamonsu database.
  postgresql_db:
    name: mamonsu
    state: present
    port: "{{ postgresql_port }}"
    owner: mamonsu
  become_user: postgres

- name: Bootstrap DDL for monitoring
  shell: mamonsu bootstrap -M mamonsu --port="{{ postgresql_port }}" mamonsu
  become_user: postgres
  ignore_errors: yes
  notify:
    - restart mamonsu

- name: Start monitoring service.
  service: 
     daemon_reload: yes
     name: mamonsu
     state: started
     enabled: yes

- name: Install zabbix-api on ansible host.
  local_action:
    module: pip
    name: zabbix-api
  run_once: true

#Right now getting HTTP Error 500: Internal Server Error. 
#- name: Import mamonsu template.
#  shell: mamonsu zabbix template export /usr/share/mamonsu/template.xml --url="{{ zabbix_url }}" --user=Admin --password=zabbix
#  run_once: true
#  ignore_errors: yes

- name: Create new of update existing zabbix host. 
  local_action:
    module: zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: Admin
    login_password: zabbix
    host_name: "{{ agent_name }}"
    visible_name: "{{ agent_name }}"
    host_groups:
      - Linux servers
      - PostgreSQL
      - "{{ zabbix_group }}"
    link_templates:
      - Template OS Linux
      - PostgresPro-Linux
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: "{{ agent_name }}"
        port: 10050
